algoritmo "Exercicio de fixação"

var
produto1, produto2, genero: caractere
preco1, preco2: real
idade, codigo: inteiro


inicio
produto1 <- "Computador"
produto2 <- "TV"
preco1 <- 2100.50
preco2 <- 1830.50
idade <- 30
codigo <- 5291
genero <- "F"

escreval (" O produto ", produto1, " custa" , preco1)
escreval (" O produto ", produto2, " custa" , preco2)
escreval (" Codigo", codigo)
escreval (" Dados da pessoal: Genero: " , genero , " e idade:",idade)

fimalgoritmo
