algoritmo "idade"
var
nome1, nome2: caractere
idade1, idade2, idadeMedia: real
inicio
escreva ("Digite o nome da primeira pessoa: ")
leia (nome1)
escreva ("Idade: ")
leia (idade1)
escreva ("Digite o nome da segunda pessoa: ")
leia (nome2)
escreva ("Idade: ")
leia (idade2)
idadeMedia <- (idade1 + idade2)/2
escreval ("A idade media entre ", nome1 , " e ", nome2 , " eh de", idadeMedia)


fimalgoritmo
